#include "buttons.h"
void button_init()
{
    SET_BIT(RCC->AHB2ENR, RCC_AHB2ENR_GPIOCEN);
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE13_Msk);
    SET_BIT(EXTI->IMR1, EXTI_IMR1_IM13);
    SET_BIT(EXTI->FTSR1, EXTI_FTSR1_FT13);

    SET_BIT(SYSCFG->EXTICR[4], SYSCFG_EXTICR4_EXTI13_PC);

}